### PR TITLE
adding functionality to set output video file from CameraView

### PR DESCRIPTION
**Pull request by tigranbs**
I've needed this functionality right a way, so I've hacked around code.
If this is applicable for your code design accept this pull request 👍

### CODE REVIEW

**Comment by Anmol92verma** [comment]
Please can anyone merge this PR ?

**Comment by austinkettner** [comment]
@Anmol92verma We will get it in this week.

**Comment by austinkettner** [comment]
@tigranbs For us to merge this in, we would need you to grab the latest upstream changes and resolve the merge conflicts.

**Comment by austinkettner** [comment]
Closing until a merge conflict resolution commit is in! Happy to merge is and reOpen this once available =)

**Pull request closed without merging**
