### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by asood123**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/CameraKit-Android ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by austinkettner** [comment]
Awesome, thanks @asood123 going to review and report back soon, then we will be good to merge!

**Comment by austinkettner** [comment]
@asood123 Was going to suggest some small edits, but going to merge and then make these in our update-docs branch. Will keep you in the loop via mentions though!

**Comment by asood123** [comment]
Sounds good, thanks.

**Comment by austinkettner** [comment]
Hey @asood123 can you take a look at the current README on the `develop` branch and outline why the images in the OpenCollective section appear broken for backers and sponsors?

Thanks in advance! =)

**Comment by asood123** [comment]
@austinkettner I don't see a `develop` branch?

**Comment by austinkettner** [comment]
My bad @asood123 I meant`master` =P

**Comment by asood123** [comment]
We store the collective slug in lowercase and it's coded as uppercase in README. You can either lowercase it or wait for this fix to be pushed later today: https://github.com/opencollective/opencollective-api/pull/1069

**Comment by asood123** [comment]
pushed, image issue is fixed

**Comment by austinkettner** [comment]
Thanks @asood123 - for the 'Become a Sponsor' it currently 404's where should that link?

**Comment by austinkettner** [comment]
Thanks @asood123 much appreciated!

**Pull request merged**
