### PR TITLE
Orientation hint fix

### PR DESCRIPTION
**Pull request by yatsinar**
There's currently a bug while setting orientation hint in Camera1: current formula doesn't respect the fact that sensor might be installed reversed on the device (like on Nexuses) which causes photo and video rotated in the result file (while preview is actually okay).
Open issues probably related to this bug:
https://github.com/gogopop/CameraKit-Android/issues/14
https://github.com/gogopop/CameraKit-Android/issues/67
Peeped this solution here:
https://github.com/googlesamples/android-Camera2Video/blob/master/Application/src/main/java/com/example/android/camera2video/Camera2VideoFragment.java

Additional minor change is the ability to record video muted. Added style parameter ckAudioEnabled which is true by default. 
Disable sound recording feature request: 
https://github.com/gogopop/CameraKit-Android/issues/121

P.S. First commit called "Speech recognition audio_type support" because I initially tried to allow SpeechRecognizer work simultaneously with video recording which turned out to be impossible, and I decided just to mute audio.

### CODE REVIEW

**Comment by awidiyadew** [comment]
This is just for video recording?
After compiling this change, Picture result from camera still rotated 90 degree on my Sony Xperia Z5.

**Comment by yatsinar** [comment]
@awidiyadew does standard android gallery displays result images rotated as well? This might be exif issue - the bitmap is actually rotated inside result but file contains exif info how to rotate it back. 
Usually it's not enough just to read bitmap from file and set it into ImageView. You either need to apply rotation matrix to an ImageView accordingly to exif or to rotate the bitmap you get in result from camera

**Comment by droidpl** [comment]
For me this solution works in all orientations but landscape with facing camera. It needs an additional flip from top to bottom

**Comment by austinkettner** [comment]
Hey @yatsinar we really appreciate the work here and look forward to more potential PRs, but due to the merge conflict we won't be merging this in currently. 100% open to reexamining if resolved though.

We have been picking up the pace dramatically lately on CameraKit, look for many more enhancements in the coming months. 0.12.0 is slated to be released this week!

@droidpl @awidiyadew

**Pull request closed without merging**
